# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "computer-science-heidelberg-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Adam McKellar"]
license = "Unlicense"
description = "Template structured to the requirements of the Heidelberg University regarding CS thesis. "
repository = "https://github.com/WyvernIXTL/computer-science-heidelberg-thesis-typst-template"
keywords = ["template"]
categories = ["paper", "report"]
disciplines = ["computer-science"]
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
